### ISSUE TITLE
Full-text search is blocking UI on page load

### ISSUE THREAD

**Issue by Janaka-Steph** [i11ume/ghostHunter#10]
Hi! I use the Techno theme on my Ghost blog and the full-text search is blocking UI on page load (the initSearch() function in the default.js file). If I disable initSearch(), everything goes fine (except for the search function obviously ^^). I have a css animation on the homepage and it only runs after a delay, more than 10 seconds on my android phone.
On my blog I have only one article but he is very long (14200 words).

Here is my website : http://www.protection-cultures-histoire.fr/
Here is the repo of the website : https://github.com/Janaka-Steph/protection-cultures-histoire.fr

Thank you for your help.

**Comment by i11ume** [comment]
Hi Janaka-Steph, unfortunately this script was a temporary solution since Ghost doesn't provide search. It has to re-index all your posts at every page load and set up a mini search engine. For small blogs this works, but it seems you have a lot of text and that means the indexing is slow.

Unfortunately there's nothing that can be done about this, but I'm working on version 2 of ghost hunter which will do all the work server-side as a ghost app. I'm just waiting on ghost to finalize their app API so I can finish it and set it up. Until then I'm afraid there's nothing I can do.

**Comment by Janaka-Steph** [comment]
Thank you for your quick reply! I am glad to hear that we can do full-text search on server side, I was not sure about that. It's ok, I will wait for the update. This function is not essential for my blog since I have just one blog post for now. 
I will check the repo from time to time. Thanks!
